### ISSUE TITLE
SOURCE as argument

### ISSUE THREAD

**Issue by markdynamo6** [artemrys/google-cloud-functions-deploy#1]
Cheers for your work on this Artem.

Any chance of having SOURCE as an argument [default = .] ?

**Comment by artemrys** [comment]
Thanks, I'll check it out today

**Comment by artemrys** [comment]
@markdynamo6 I have no time to work on this one and environment to test the feature, but I will accept a PR :)

**Comment by artemrys** [comment]
I released [v0.2.0](https://hub.docker.com/repository/docker/artemrys/google-cloud-functions-deploy/tags?page=1&ordering=last_updated) with the possibility to specify custom `SOURCE`. If not specified, `.` will be used.
