### ISSUE TITLE
Pipe always deploys a http trigger function

### ISSUE THREAD

**Issue by yonner** [artemrys/google-cloud-functions-deploy#3]
Hi,

After searching around the web to deploy my google cloud functions from bitbucket I found your repo and successfully deployed my http trigger function.

However i tried to use the same pipe to deploy my event trigger function and noticed that your code always deploys as a http trigger even if you specify "--trigger-event" in the EXTRA_ARGS parameter. If you could make this configurable that would be extremely useful.

**Comment by artemrys** [comment]
Hi

I'll try to take a look today.

**Comment by yonner** [comment]
Hi just noticed you picked this up awesome 👍 did you make any progress?

**Comment by artemrys** [comment]
Working on it right now, hope to finish today, need to rebuild all the test infrastructure.

**Comment by artemrys** [comment]
I released [v0.2.0](https://hub.docker.com/repository/docker/artemrys/google-cloud-functions-deploy/tags?page=1&ordering=last_updated) with the ability to specify [`TRIGGER`](https://cloud.google.com/functions/docs/concepts/events-triggers). If it is not specified, then `--trigger-http` will be used.

**Comment by yonner** [comment]
Thanks for doing that, will give it a try tomorrow.

**Comment by yonner** [comment]
This works perfectly and exactly what I was looking for....Thanks
